In [3]:
import pandas as pd
df = pd.read_csv('../data/olympics.csv', sep=';')
df.head()

,ID,Name,Sex,Age,Height,Weight,Year,Sport,Event,Medal,NOC,Country
0,1,A Dijiang,M,24,1800.0,800.0,1992,Basketball,Basketball Men's Basketball,NaN,CHN,China
1,2,A Lamusi,M,23,1700.0,600.0,2012,Judo,Judo Men's Extra-Lightweight,NaN,CHN,China
2,3,Gunnar Nielsen Aaby,M,24,NaN,NaN,1920,Football,Football Men's Football,NaN,DEN,Denmark
3,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18,1680.0,NaN,1932,Athletics,Athletics Women's 100 metres,NaN,NED,Netherlands
4,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18,1680.0,NaN,1932,Athletics,Athletics Women's 4 x 100 metres Relay,NaN,NED,Netherlands

In [5]:
#Athleten ohne Größe, Gewicht und Country löschen
df = df.dropna(subset=['Height', 'Weight'])
df = df.dropna(subset=['Country'])
#Fehlende Werte für Medaillien löschen
df['Medal'] = df['Medal'].fillna('None')

In [7]:
df.describe()

,ID,Age,Height,Weight,Year
count,166760.000000,166760.000000,166760.000000,166760.000000,166760.000000
mean,68218.528070,24.950144,1755.349065,706.594267,1988.683761
std,39138.559273,5.863479,109.486740,147.954237,20.510546
min,1.000000,0.000000,1270.000000,250.000000,1904.000000
25%,34367.000000,21.000000,1680.000000,600.000000,1972.000000
50%,68613.000000,24.000000,1750.000000,700.000000,1992.000000
75%,101942.000000,28.000000,1830.000000,790.000000,2004.000000
max,135568.000000,71.000000,2260.000000,2140.000000,2016.000000